format = """
$directory$git_branch$git_status$cmd_duration
$character"""

[directory]
style = "bold cyan"

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[git_branch]
format = "[$branch]($style) "
style = "bold black"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold red"

[cmd_duration]
format = "[$duration]($style) "
style = "bold yellow"
